#!/bin/csh
javac -classpath .:/home/pgr/jaxoapps/jaxogram/war/WEB-INF/lib/orkut-os-client-2.0.02.jar Sample.java
java -classpath .:/home/pgr/jaxoapps/jaxogram/war/WEB-INF/lib/orkut-os-client-2.0.02.jar Sample
