#!/bin/csh
cd war
rm jaxogram.zip
zip jaxogram -r manifest.webapp index.html favicon.ico js style applogos images
mv jaxogram.zip '/home/pgr/.gvfs/build on ottokar/sites/jaxogram'

cat > '/home/pgr/.gvfs/build on ottokar/sites/jaxogram/install.html' << End-Of-File
<html>
 <body>
   <p>Packaged app installation page</p>
   <script>
     var manifestUrl = 'http://ottokar/jaxogram/package.manifest';
     try {
        var req = navigator.mozApps.installPackage(manifestUrl);
        req.onsuccess = function() {
          alert(this.result.origin);
        };
        req.onerror = function() {
          alert(this.error.name);
        };
     }catch (error) {
        alert(error);
     }
   </script>
 </body>
</html>
End-Of-File

cat > '/home/pgr/.gvfs/build on ottokar/sites/jaxogram/package.manifest'  << End-Of-File
{
  "name": "Jaxogram",
  "package_path": "http://ottokar/jaxogram/jaxogram.zip",
  "version": "0.9.2",
  "developer": {
    "name": "Jaxo, Inc.",
    "url": "http://www.jaxo.com"
  }
}
End-Of-File


